server.port=8080

spring.datasource.url=jdbc:mysql://mainline.proxy.rlwy.net:25781/railway
spring.datasource.username=root
spring.datasource.password=sSPYblKJFVzQxclpWuZrQpLuJYnqkuKC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect